export const SEQUELIZE='SEQUELIZE'

export const POSTGRES_USERNAME='POSTGRES_USERNAME'
export const POSTGRES_PASSWORD='POSTGRES_PASSWORD'
export const POSTGRES_HOST='POSTGRES_HOST'
export const POSTGRES_PORT='POSTGRES_PORT'
export const POSTGRES_DATABASE='POSTGRES_DATABASE'
export const POSTGRES_DIALECT='POSTGRES_DIALECT'

// * Node-env config
export const DEVELOPMENT = 'development';
export const PRODUCTION = 'production';

// * Repos
export const STATUS_REPOSITORY = 'STATUS_REPOSITORY';
export const DELIVERY_REPOSITORY = 'DELIVERY_REPOSITORY';
export const TOWN_REPOSITORY = 'TOWN_REPOSITORY';
export const TYPE_REPOSITORY = 'TYPE_REPOSITORY';
